#!/bin/bash
isExisthttpd = `pgrep httpd`
if [[ -n  $isExistApp ]]; then
    service httpd stop        
fi

isExistapache2 = `pgrep apache2`
if [[ -n  $isExistapache2 ]]; then
    service apache2 stop        
fi
